image: node:15.4.0

variables:
  PUBLIC_URL: admin-webapp

cache:
  paths:
    - node_modules/

before_script:
  - npm install
  - npm install --save gh-pages

test:
  stage: test
  script:
    - npm test

pages:
  stage: deploy
  script:
    - npm run deploy
    - cp public/index.html public/404.html
    - mv public _public
    - mv build public
  artifacts:
    paths:
    - public
  only:
    - cosi_dev
