image: node:15.4.0


pages:
  variables:
    PUBLIC_URL: admin-webapp
  cache:
    paths:
    - node_modules/
  stage: deploy
  script:
    - npm install
    - npm run build --prod
    - cp public/index.html public/404.html
    - mv public _public
    - mv build public
  artifacts:
    paths:
    - public
  only:
    - cosi_dev
